version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    groups:
      update-patch-minor:
        patterns: ['*']
        update-types:
          - 'minor'
          - 'patch'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/'
    ignore:
      - dependency-name: '*'
        update-types:
          ['version-update:semver-minor', 'version-update:semver-patch']
    schedule:
      interval: 'weekly'
