version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    groups:
      update:
        patterns: ['*']
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    schedule:
      interval: 'weekly'
