ci:
  assert:
    assertions:
      categories:accessibility: [error, minScore: 0.94]
      categories:best-practices: [error, minScore: 1]
      categories:performance: [error, minScore: 0.68]
      categories:seo: [error, minScore: 0.92]
    includePassedAssertions: true
  collect:
    numberOfRuns: 1
    startServerCommand: http-server dist-ssr --brotli -c31536000
    startServerReadyPattern: Hit CTRL-C to stop the server
    url:
      - http://localhost:8080/en
  upload:
    outputDir: .lighthouseci/results
    target: filesystem
