version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

executors:
  node:
    docker:
      - image: cimg/node:18.18
  node-browsers:
    docker:
      - image: cimg/node:18.18-browsers

jobs:
  execute-npm:
    parameters:
      executor:
        type: executor
        default: node
      npm-run-command:
        type: string
      setup:
        type: steps
        default: []
    executor: << parameters.executor >>
    steps:
      - checkout
      - steps: << parameters.setup >>
      - run: npm ci
      - run: npm run << parameters.npm-run-command >>

workflows:
  main:
    jobs:
      - execute-npm:
          name: npm run check-types
          npm-run-command: check-types
      - execute-npm:
          name: npm run lint
          npm-run-command: lint
      - execute-npm:
          executor: node-browsers
          name: npm run lighthouse
          npm-run-command: lighthouse
          setup:
            - browser-tools/install-chrome
      - execute-npm:
          name: npm run prettier
          npm-run-command: prettier
