version: 2.1

jobs:
  execute-npm:
    parameters:
      npm-run-command:
        type: string
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run: npm ci
      - run: npm run << parameters.npm-run-command >>

workflows:
  main:
    jobs:
      - execute-npm:
          name: npm run build
          npm-run-command: build
      - execute-npm:
          name: npm run types
          npm-run-command: types
      - execute-npm:
          name: npm run lint
          npm-run-command: lint
      - execute-npm:
          name: npm run prettier
          npm-run-command: prettier
