version: 2.1

jobs:
  execute-npm:
    parameters:
      npm-run-command:
        type: string
    docker:
      - image: cimg/node:18.17
        environment:
          # With a PISA_URL environment variable the build will not contain fake LocalStorage
          # data classes. Given that it's easier to see the actual package size,
          # without artificial fake data.
          PISA_URL: 'some-fake-pisa-url'
    steps:
      - checkout
      - run: npm ci
      - run: npm run << parameters.npm-run-command >>

workflows:
  main:
    jobs:
      - execute-npm:
          name: npm run build
          npm-run-command: build
      - execute-npm:
          name: npm run eslint
          npm-run-command: eslint
      - execute-npm:
          name: npm run prettier
          npm-run-command: prettier
